"""
Relationships page (Phase 4).

Automatically generates relationships for any evidence whose entities
haven't been processed yet (tracked in services/relationship_store.py),
then shows a summary, relationship-type breakdown, a filterable table,
an interactive knowledge graph, and an entity connection search.

Every relationship shown here was generated by services/relationship_analysis.py
from entities that share a source context (row/page/document) — see
that module for the exact rules. Nothing here infers ownership, guilt,
or intent; relationships only describe shared evidence context.
"""

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from services import entity_store, relationship_store, relationship_analysis, graph_service

_ENTITY_TYPE_COLORS = {
    "PERSON": "#4C78A8",
    "ORGANIZATION": "#F58518",
    "LOCATION": "#54A24B",
    "DATE": "#B279A2",
    "EMAIL": "#E45756",
    "PHONE": "#72B7B2",
    "ACCOUNT": "#EECA3B",
    "URL": "#9D755D",
    "IP_ADDRESS": "#BAB0AC",
    "TRANSACTION_ID": "#FF9DA6",
}

MAX_GRAPH_EDGES = 150


def _run_relationship_generation():
    """Generates relationships for any evidence whose entities haven't
    been turned into relationships yet. Returns nothing to show inline —
    generation is silent unless it fails, matching the Entities page."""
    extracted_ids = {e["evidence_id"] for e in entity_store.load_entities()}
    pending = [eid for eid in extracted_ids if not relationship_store.already_processed(eid)]

    if not pending:
        return

    with st.spinner(f"Analyzing relationships for {len(pending)} evidence item(s)..."):
        for evidence_id in pending:
            entities = entity_store.get_by_evidence(evidence_id)
            try:
                relationships = relationship_analysis.generate_relationships(entities)
            except Exception as e:
                relationships = []
                st.warning(f"Relationship analysis failed for {evidence_id}: {e}")
            relationship_store.add_relationships(evidence_id, relationships)


def _build_plotly_figure(G, relationships_subset):
    if G.number_of_nodes() == 0:
        return None

    import networkx as nx
    pos = nx.spring_layout(G, seed=42, k=0.8 / max(G.number_of_nodes(), 1) ** 0.5)

    edge_x, edge_y = [], []
    mid_x, mid_y, mid_text = [], [], []
    for u, v, data in G.edges(data=True):
        x0, y0 = pos[u]
        x1, y1 = pos[v]
        edge_x += [x0, x1, None]
        edge_y += [y0, y1, None]
        mid_x.append((x0 + x1) / 2)
        mid_y.append((y0 + y1) / 2)
        mid_text.append(
            f"{data.get('relationship_type')}<br>"
            f"Evidence: {data.get('evidence_id')} ({data.get('source_filename')})<br>"
            f"Record/Page: {data.get('record_number') or data.get('page_number') or '-'}<br>"
            f"Method: {data.get('method')} | Confidence: {data.get('confidence')}"
        )

    edge_trace = go.Scatter(
        x=edge_x, y=edge_y, mode="lines",
        line=dict(width=1, color="#B0B0B0"), hoverinfo="none",
    )
    edge_hover_trace = go.Scatter(
        x=mid_x, y=mid_y, mode="markers",
        marker=dict(size=6, color="#B0B0B0", opacity=0),
        hovertext=mid_text, hoverinfo="text",
    )

    node_x, node_y, node_text, node_hover, node_color = [], [], [], [], []
    for node_id, data in G.nodes(data=True):
        x, y = pos[node_id]
        node_x.append(x)
        node_y.append(y)
        node_text.append(data.get("entity_text", "")[:20])
        node_hover.append(f"{data.get('entity_text')} ({data.get('entity_type')})")
        node_color.append(_ENTITY_TYPE_COLORS.get(data.get("entity_type"), "#999999"))

    node_trace = go.Scatter(
        x=node_x, y=node_y, mode="markers+text", text=node_text,
        textposition="top center", hovertext=node_hover, hoverinfo="text",
        marker=dict(size=16, color=node_color, line=dict(width=1, color="white")),
    )

    fig = go.Figure(data=[edge_trace, edge_hover_trace, node_trace])
    fig.update_layout(
        showlegend=False, hovermode="closest",
        margin=dict(l=10, r=10, t=10, b=10),
        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        height=520,
    )
    return fig


def render():
    st.header("Relationships & Knowledge Graph")
    st.caption(
        "Relationships connect entities that appear together in the same evidence "
        "context (row, page, or document). A relationship shows the evidence "
        "contains these entities together — it does not confirm ownership, "
        "identity, or intent, and does not imply wrongdoing."
    )

    entities = entity_store.load_entities()
    if not entities:
        st.info("No entities have been extracted yet. Go to **Entities** (after uploading evidence) first.")
        return

    _run_relationship_generation()

    relationships = relationship_store.load_relationships()
    if not relationships:
        st.info(
            "No relationships could be generated yet. This can happen if the "
            "evidence doesn't contain at least two compatible entity types "
            "(e.g. a PERSON and an EMAIL) within the same record or page."
        )
        return

    G_full = graph_service.build_graph(relationships)
    df = pd.DataFrame(relationships)

    # ---------------------------------------------------------------
    # A. Summary
    # ---------------------------------------------------------------
    st.subheader("Summary")
    summary = graph_service.graph_summary(G_full)
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Relationships", len(relationships))
    c2.metric("Total Graph Nodes", summary["nodes"])
    c3.metric("Total Graph Edges", summary["edges"])
    c4.metric("Relationship Types", df["relationship_type"].nunique())

    # ---------------------------------------------------------------
    # B. Relationship type summary
    # ---------------------------------------------------------------
    st.subheader("Relationship Type Summary")
    type_counts = df["relationship_type"].value_counts()
    cols = st.columns(min(len(type_counts), 6) or 1)
    for i, (rel_type, count) in enumerate(type_counts.items()):
        cols[i % len(cols)].metric(rel_type.replace("_", " ").title(), int(count))

    st.divider()

    # ---------------------------------------------------------------
    # Filters (shared by table + graph)
    # ---------------------------------------------------------------
    st.subheader("Relationship Table")
    f1, f2, f3 = st.columns(3)
    type_filter = f1.multiselect("Relationship type", sorted(df["relationship_type"].unique()))
    evidence_filter = f2.multiselect("Evidence ID", sorted(df["evidence_id"].unique()))
    file_filter = f3.multiselect("Source file", sorted(df["source_filename"].unique()))

    f4, f5, f6 = st.columns(3)
    source_type_filter = f4.multiselect("Source entity type", sorted(df["source_entity_type"].unique()))
    target_type_filter = f5.multiselect("Target entity type", sorted(df["target_entity_type"].unique()))
    search_text = f6.text_input("Search text (source or target)")

    filtered = df.copy()
    if type_filter:
        filtered = filtered[filtered["relationship_type"].isin(type_filter)]
    if evidence_filter:
        filtered = filtered[filtered["evidence_id"].isin(evidence_filter)]
    if file_filter:
        filtered = filtered[filtered["source_filename"].isin(file_filter)]
    if source_type_filter:
        filtered = filtered[filtered["source_entity_type"].isin(source_type_filter)]
    if target_type_filter:
        filtered = filtered[filtered["target_entity_type"].isin(target_type_filter)]
    if search_text:
        needle = search_text.strip().lower()
        filtered = filtered[
            filtered["source_entity_text"].str.lower().str.contains(needle, na=False)
            | filtered["target_entity_text"].str.lower().str.contains(needle, na=False)
        ]

    display_cols = {
        "source_entity_text": "Source Entity",
        "source_entity_type": "Source Type",
        "relationship_type": "Relationship",
        "target_entity_text": "Target Entity",
        "target_entity_type": "Target Type",
        "evidence_id": "Evidence ID",
        "source_filename": "Source File",
        "record_number": "Record #",
        "page_number": "Page #",
        "method": "Method",
        "confidence": "Confidence",
    }
    shown = filtered[list(display_cols.keys())].rename(columns=display_cols)
    st.dataframe(shown, use_container_width=True, hide_index=True)
    st.caption(f"Showing {len(shown)} of {len(relationships)} total relationships.")

    st.divider()

    # ---------------------------------------------------------------
    # C. Knowledge graph visualization (built from the FILTERED set)
    # ---------------------------------------------------------------
    st.subheader("Knowledge Graph")
    graph_relationships = filtered.to_dict("records")
    truncated = False
    if len(graph_relationships) > MAX_GRAPH_EDGES:
        truncated = True
        graph_relationships = graph_relationships[:MAX_GRAPH_EDGES]

    if truncated:
        st.warning(
            f"Showing the first {MAX_GRAPH_EDGES} of {len(filtered)} filtered relationships "
            "in the graph. Use the filters above to narrow the view."
        )

    if not graph_relationships:
        st.write("No relationships match the current filters.")
    else:
        G_display = graph_service.build_graph(graph_relationships)
        fig = _build_plotly_figure(G_display, graph_relationships)
        if fig is not None:
            st.plotly_chart(fig, use_container_width=True)
        entity_types_shown = sorted({r["source_entity_type"] for r in graph_relationships} | {r["target_entity_type"] for r in graph_relationships})
        st.caption("Entity types shown: " + " · ".join(entity_types_shown))

    st.divider()

    # ---------------------------------------------------------------
    # Entity connection search (always searches the FULL graph, not the
    # filtered one, so investigators can find any entity regardless of
    # the current table filters).
    # ---------------------------------------------------------------
    st.subheader("Find Connections for an Entity")
    search_entity = st.text_input("Search for an entity (e.g. a name, email, or account)", key="entity_connection_search")

    if search_entity:
        matches = graph_service.find_entity_nodes(G_full, search_entity)
        if not matches:
            st.write("No matching entity found in the knowledge graph.")
        else:
            options = {f"{text} ({etype})": node_id for node_id, text, etype in matches}
            choice_label = st.selectbox("Matching entities", list(options.keys()))
            node_id = options[choice_label]
            connections = graph_service.get_connections(G_full, node_id)

            if not connections:
                st.write("This entity has no recorded connections.")
            else:
                st.write(f"**{choice_label}** — {len(connections)} connection(s):")
                for conn in connections:
                    if conn["direction"] == "outgoing":
                        line = f"**{conn['relationship_type']}** → {conn['other_entity_text']} ({conn['other_entity_type']})"
                    else:
                        line = f"{conn['other_entity_text']} ({conn['other_entity_type']}) → **{conn['relationship_type']}** → this entity"
                    with st.container(border=True):
                        st.write(line)
                        st.caption(
                            f"Evidence: {conn['evidence_id']} ({conn['source_filename']}) | "
                            f"Record/Page: {conn.get('record_number') or conn.get('page_number') or '-'} | "
                            f"Method: {conn.get('method')}"
                        )
